# Generated by Django 3.0 on 2019-12-15 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visitor',
            new_name='Entries',
        ),
    ]
