# Generated by Django 3.0 on 2019-12-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20191214_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entries',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='entries',
            name='lastName',
        ),
        migrations.AddField(
            model_name='entries',
            name='fullName',
            field=models.CharField(default='default name', max_length=120),
        ),
    ]
