# Generated by Django 3.0 on 2019-12-15 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_auto_20191214_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entries',
            old_name='fullName',
            new_name='name',
        ),
    ]
