# Generated by Django 3.0 on 2019-12-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_auto_20191214_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entries',
            old_name='signOut_date',
            new_name='signout_date',
        ),
        migrations.AddField(
            model_name='entries',
            name='is_signout',
            field=models.BooleanField(default=False),
        ),
    ]
