# Generated by Django 3.0 on 2019-12-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_auto_20191216_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='signout_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
